#!/usr/bin/env node
/**
 * Bundles the current menu into the app so it works offline from the very first launch:
 *   - src/data/menu-snapshot.json      categories, products and every dish's details
 *   - assets/menu/*                     every dish photo, phone-sized
 *   - src/data/menu-snapshot-images.ts  photo URL -> bundled file (require map)
 *
 * Run before each build:  npm run snapshot:menu
 * The app still prefers live data when online; this is only the offline baseline.
 */
import { createHash } from 'node:crypto';
import { mkdir, readdir, readFile, rm, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

// Same resizing the app applies, so bundled photos match the URLs it requests.
import { sizedImageUrl } from '../src/utils/image-url.ts';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const IMAGES_DIR = join(root, 'assets', 'menu');
const SNAPSHOT_FILE = join(root, 'src', 'data', 'menu-snapshot.json');
const IMAGES_MAP_FILE = join(root, 'src', 'data', 'menu-snapshot-images.ts');

// The API allows 60 requests/min; stay well below it.
const API_DELAY_MS = 1300;
const PER_CATEGORY_LIMIT = 100;

const config = await readFile(join(root, 'src', 'config', 'api.ts'), 'utf8');
const BASE_URL = config.match(/API_BASE_URL\s*=\s*'([^']+)'/)?.[1];
if (!BASE_URL?.startsWith('https://')) throw new Error('API_BASE_URL not found in src/config/api.ts');

const sleep = (ms) => new Promise((resolve) => setTimeout(resolve, ms));

async function api(path, attempt = 1) {
  const res = await fetch(`${BASE_URL}${path}`, { headers: { Accept: 'application/json' } });
  if (res.status === 429 && attempt <= 3) {
    const wait = Number(res.headers.get('retry-after') ?? 60);
    console.log(`  límite de peticiones; esperando ${wait}s…`);
    await sleep(wait * 1000);
    return api(path, attempt + 1);
  }
  if (!res.ok) throw new Error(`${path} -> HTTP ${res.status}`);
  await sleep(API_DELAY_MS);
  return res.json();
}

const list = (body) => (Array.isArray(body) ? body : Array.isArray(body?.data) ? body.data : []);

console.log('1/3 Menú…');
const categories = list(await api('/public/categories')).filter((c) => typeof c === 'string');
const products = {};
for (const name of categories) {
  products[name] = list(await api(`/public/products?category=${encodeURIComponent(name)}&limit=${PER_CATEGORY_LIMIT}`));
  console.log(`  ${name}: ${products[name].length}`);
}

const allProducts = Object.values(products).flat();
const ids = [...new Set(allProducts.map((p) => p.id).filter(Number.isInteger))];

console.log(`2/3 Ingredientes de ${ids.length} platillos (≈${Math.ceil((ids.length * API_DELAY_MS) / 60000)} min)…`);
const details = {};
let done = 0;
for (const id of ids) {
  try {
    details[id] = await api(`/app/products/${id}`);
  } catch (err) {
    console.log(`  sin detalle para ${id}: ${err.message}`);
  }
  if (++done % 25 === 0) console.log(`  ${done}/${ids.length}`);
}

console.log('3/3 Fotos…');
const urls = [
  ...new Set(
    allProducts
      .map((p) => (typeof p.image === 'string' && p.image.startsWith('https://') ? sizedImageUrl(p.image) : null))
      .filter(Boolean),
  ),
];
await rm(IMAGES_DIR, { recursive: true, force: true });
await mkdir(IMAGES_DIR, { recursive: true });

const EXTENSIONS = { 'image/webp': 'webp', 'image/jpeg': 'jpg', 'image/png': 'png' };
const images = {};
let bytes = 0;
for (const url of urls) {
  try {
    const res = await fetch(url, { headers: { Accept: 'image/webp,image/jpeg,image/png' } });
    const type = (res.headers.get('content-type') ?? '').split(';')[0];
    const ext = EXTENSIONS[type];
    if (!res.ok || !ext) throw new Error(`HTTP ${res.status} ${type}`);
    const data = Buffer.from(await res.arrayBuffer());
    const file = `${createHash('sha1').update(url).digest('hex').slice(0, 16)}.${ext}`;
    await writeFile(join(IMAGES_DIR, file), data);
    images[url] = file;
    bytes += data.length;
  } catch (err) {
    console.log(`  no se pudo descargar ${url}: ${err.message}`);
  }
}

await mkdir(dirname(SNAPSHOT_FILE), { recursive: true });
await writeFile(
  SNAPSHOT_FILE,
  JSON.stringify({ version: 1, generatedAt: Date.now(), categories, products, details }),
);

const entries = Object.entries(images)
  .sort(([a], [b]) => a.localeCompare(b))
  .map(([url, file]) => `  ${JSON.stringify(url)}: require('@/assets/menu/${file}'),`)
  .join('\n');
await writeFile(
  IMAGES_MAP_FILE,
  `// Generated by scripts/snapshot-menu.mjs — do not edit by hand.\n` +
    `// Dish photos bundled in the app, keyed by the (phone-sized) URL the menu uses.\n` +
    `export const SNAPSHOT_IMAGES: Record<string, number> = {\n${entries}\n};\n`,
);

const files = await readdir(IMAGES_DIR);
console.log(
  `Listo: ${categories.length} categorías, ${allProducts.length} platillos, ` +
    `${Object.keys(details).length} con ingredientes, ${files.length} fotos (${(bytes / 1024 / 1024).toFixed(1)} MB).`,
);
