import { toProductDetail, toProducts, type ProductDetail } from '@/api/catalog';
import type { Category } from '@/types/product';

/**
 * Menu bundled inside the app (generated by `npm run snapshot:menu`), so the menu, every
 * dish's ingredients and photos are there even on a first launch without internet.
 * Live data from the server always takes priority when there is a connection.
 */
type SnapshotFile = {
  version: number;
  generatedAt: number;
  categories: string[];
  products: Record<string, unknown[]>;
  details: Record<string, unknown>;
};

const raw = require('./menu-snapshot.json') as SnapshotFile;

/** When the bundled copy was generated. */
export const SNAPSHOT_AT = raw.generatedAt;

let menu: Category[] | null = null;
let details: Map<number, ProductDetail> | null = null;

export function snapshotMenu(): Category[] {
  menu ??= raw.categories
    .map((name) => ({ name, products: toProducts(raw.products[name] ?? []) }))
    .filter((category) => category.products.length > 0);
  return menu;
}

export function snapshotDetails(): Map<number, ProductDetail> {
  details ??= new Map(
    Object.entries(raw.details).map(([id, data]) => [Number(id), toProductDetail(data)]),
  );
  return details;
}
